### PR TITLE
Access token

### PR DESCRIPTION
**Pull request by ajay2507**
Implemented getAccessToken method and GetItem method.

Reference: https://developer.ebay.com/api-docs/static/oauth-tokens.html

### CODE REVIEW

**Comment by narraressan** [comment]
HI! 

I'd like to ask. If I have this code 

```
let ebay = new Ebay({
		clientID: "my-ClientID",
		clientSecret: 'my-Secret',
		body: {
			grant_type: "authorization_code",
			redirect_uri: 'XXXXX_ZZZZZ-AxxxxLad-Zogxsx-oirlx',
			code: params.code
		}
	})

	ebay.getAccessToken()
	.then(
		(data) => {
			res.json(data) // data.access_token
		},
		(error) => {
			res.json(error)
		}
	)
```

I get an error saying
`{"error":"invalid_grant","error_description":"the provided authorization grant code is invalid or was issued to another client"}`

but if only use client_credentials instead of authorization_code I get a token, 
```
body: {
	grant_type: "client_credentials"
}
```

The problem is, I need a User Access Token (authorization_code) not Application Access Token (client_credentials)

Anyone knows how to fix this? 

Thank you...

**Comment by ajay2507** [comment]
@narraressan  Can you create a separate issue for this?.

**Comment by narraressan** [comment]
Good day!

Sorry for the late reply.
Actually, I already got it working. And I didn't fix anything. 
It was actually a very weird occurrence because all I did was logout my Ebay account and log in again. 
I noticed that I can't get a token if I already have an account logged in.

Thank you.

**Comment by ajay2507** [comment]
@narraressan okay cool. Thanks

**Pull request merged**
